language: node_js
node_js:
- '4.1'
services:
- mongodb
before_script:
- sleep 15
- mongo mydb_test --eval 'db.addUser("travis", "test");'
before_install:
- openssl aes-256-cbc -K $encrypted_ee28590b53fb_key -iv $encrypted_ee28590b53fb_iv
  -in .env.enc -out .env -d
